# run a python program that creates a new file and stores a random number in it

name: run main.py

on:
  push:
  schedule:
    - cron: '* * * * *'

jobs:
  setup:
    runs-on: ubuntu-22.04
    container:
      image: python:3
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3
   
      - name: Execute python script
        run: python3 main.py

      - name: Commit files
        run: |
            git config --global --add safe.directory "$GITHUB_WORKSPACE"        
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add -A
            git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
      
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
